on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  workflow_dispatch:


name: Create Jira tickets for GH Issues and PRs

jobs:
  main:
    runs-on: ubuntu-latest
    name: Main
    steps:
    - name: Dump context
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - uses: actions/checkout@v2
      with:
        repository: "github/hub"
      
    - name: Check if community user
      id: vault-team-role
      run: |
        TEAM=consul
        ROLE="$(hub api orgs/hashicorp/teams/${TEAM}/memberships/${{ github.actor }} | jq -r '.role | select(.!=null)')"
        if [[ -n ${ROLE} ]]; then
          echo "Actor ${{ github.actor }} is a ${TEAM} team member, skipping Jira ticket creation"
        else
          echo "Actor ${{ github.actor }} is not a ${TEAM} team member, continuing to Jira ticket creation"
        fi
        echo "::set-output name=role::${ROLE}"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Login
      if: ${{ !steps.vault-team-role.outputs.role }}
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira ticket for Issue
      if: ${{ !steps.vault-team-role.outputs.role && github.event.issue }}
      uses: tomhjp/gajira-create@master
      with:
        project: VAULT
        issuetype: "GH Issue"
        issuelink: ${{ github.event.issue.html_url }}
        summary: "${{ github.repository }} Issue: ${{ github.event.issue.title }} #${{ github.event.issue.number }}"
        description: "${{ github.event.issue.body }}\n\n_Created from GitHub Action for ${{ github.event.issue.html_url }}, from ${{ github.actor }}_"
        fixversion: TBD
        team: product

    - name: Create Jira ticket for PR
      if: ${{ !steps.vault-team-role.outputs.role && github.event.pull_request }}
      uses: tomhjp/gajira-create@master
      with:
        project: VAULT
        issuetype: "GH Issue"
        issuelink: ${{ github.event.pull_request.html_url }}
        summary: "${{ github.repository }} PR: ${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}"
        description: "${{ github.event.pull_request.body }}\n\n_Created from GitHub Action for ${{ github.event.pull_request.html_url }}, from ${{ github.actor }}_"
        fixversion: TBD
        team: product
