on:
  issues:
    types: [opened, closed, deleted, reopened]
  pull_request:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment: # Comments on the diff
    types: [created]
  workflow_dispatch:


name: Jira Sync

jobs:
  create:
    if: (github.event_name == 'issues' || github.event_name == 'pull_request') && github.event.action == 'opened'
    runs-on: ubuntu-latest
    name: Create ticket
    steps:
    - uses: actions/checkout@v2
      with:
        repository: "github/hub"
      
    - uses: actions/github-script@v2
      id: is-community
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const team = "vault"
          const username = "${{ github.actor }}"
          const result = await github.teams.getMembershipForUserInOrg({
            org: "hashicorp",
            team_slug: team,
            username: username,
          })
          const inVaultTeam = "role" in result.data
          if (inVaultTeam) {
            console.log(`${username} is a ${team} team member, skipping Jira ticket creation`)
          } else {
            console.log(`${username} is not a ${team} team member, continuing to ticket creation`)
          }
          return !inVaultTeam

    - name: Login
      if: steps.is-community.outputs.result == 'true'
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create ticket
      if: steps.is-community.outputs.result == 'true'
      uses: tomhjp/gajira-create@master
      with:
        project: VAULT
        issuetype: "GH Issue"
        issuelink: ${{ github.event.issue.html_url || github.event.pull_request.html_url }}
        summary: "${{ github.repository }}: ${{ github.event.issue.title || github.event.pull_request.title }} #${{ github.event.issue.number || github.event.pull_request.number }}"
        description: "${{ github.event.issue.body || github.event.pull_request.body }}\n\n_Created from GitHub Action for ${{ github.event.issue.html_url || github.event.pull_request.html_url }}, from ${{ github.actor }}_"
        fixversion: TBD
        team: product
  
  sync-comment:
    if: github.event.action == 'created' || github.event.action == 'submitted'
    runs-on: ubuntu-latest
    name: Sync comment
    steps:
    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Search
      id: search
      uses: tomhjp/gh-action-jira-search@v0.2.0
      with:
        jql: 'project = "VAULT" and issuetype = "GH Issue" and cf[10089]="${{ github.event.issue.html_url || github.event.pull_request.html_url }}"' # cf[10089] == Issue Link custom field

    - name: Sync comment
      if: steps.search.outputs.issue
      uses: atlassian/gajira-comment@v2.0.1
      with:
        issue: ${{ steps.search.outputs.issue }}
        comment: "${{ github.actor }} ${{ github.event.review.state || 'commented' }}:\n\n${{ github.event.comment.body || github.event.review.body }}\n\n${{ github.event.comment.html_url || github.event.review.html_url }}"

  close:
    if: (github.event_name == 'issues' || github.event_name == 'pull_request') && (github.event.action == 'closed' || github.event.action == 'deleted')
    runs-on: ubuntu-latest
    name: Close ticket
    steps:
    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Search
      id: search
      uses: tomhjp/gh-action-jira-search@v0.2.0
      with:
        # cf[10089] == Issue Link custom field
        jql: 'project = "VAULT" and issuetype = "GH Issue" and cf[10089]="${{ github.event.issue.html_url || github.event.pull_request.html_url }}"'

    - name: Close ticket
      if: steps.search.outputs.issue
      uses: atlassian/gajira-transition@v2.0.1
      with:
        issue: ${{ steps.search.outputs.issue }}
        transition: Done

  reopen:
    if: github.event.action == 'reopened'
    runs-on: ubuntu-latest
    name: Reopen ticket
    steps:
    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Search
      id: search
      uses: tomhjp/gh-action-jira-search@v0.2.0
      with:
        # cf[10089] == Issue Link custom field
        jql: 'project = "VAULT" and issuetype = "GH Issue" and cf[10089]="${{ github.event.issue.html_url || github.event.pull_request.html_url }}"'

    - name: Reopen ticket
      if: steps.search.outputs.issue
      uses: atlassian/gajira-transition@v2.0.1
      with:
        issue: ${{ steps.search.outputs.issue }}
        transition: "To Do"
